version: '3.1'

services:
  custom-drupal:
    image: drupal:9
    build: .
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    restart: always

  postgres:
    image: postgres:14
    volumes: drupal-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - drupal

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
